const Actions = {
  CLICK_COUNTER: 'CLICK_COUNTER',
  RESET_COUNTER: 'RESET_COUNTER',
  ADD_COUNTER: 'ADD_COUNTER',
  DELETE_COUNTER: 'DELETE_COUNTER',
  SET_MAX_COUNTERS: 'SET_MAX_COUNTERS'
};

export default Actions;